### ISSUE TITLE
How do I upgrade the version of Ruby that Heroku Toolbelt uses?

### ISSUE THREAD

**Issue by marcamillion** [heroku/toolbelt#123]
I am trying to install a deploy hook to Honeybadger and it gave me an error message:

````bash
$ rake honeybadger:heroku:add_deploy_notification APP=myapp
Digest::Digest is deprecated; use Digest
Digest::Digest is deprecated; use Digest

Running:
heroku addons:add deployhooks:http --url="https://api.honeybadger.io/v1/deploys?deploy[environment]=production&deploy[local_username]={{user}}&deploy[revision]={{head}}&api_key=4b4d1b35" --app myapp
/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/definition.rb:380:in `validate_ruby!': Your Ruby version is 1.9.3, but your Gemfile specified 2.1.5 (Bundler::RubyVersionMismatch)
	from /.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler.rb:117:in `setup'
	from /.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/setup.rb:17:in `<top (required)>'
	from /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
````

I also tried running `heroku update` and nothing happened.

When I run `heroku version` this is what I see:

````bash
$ heroku version
heroku-toolbelt/3.23.3 (x86_64-darwin10.8.0) ruby/1.9.3
=== Installed Plugins
heroku-ranger
heroku-sendgrid-stats
heroku-sendgrid-test-email
````

How do I get rid of this error?

**Comment by dickeyxxx** [comment]
this is a known issue https://github.com/heroku/toolbelt/issues/63. You can't use the toolbelt in a rake task like that

**Comment by marcamillion** [comment]
So you are saying this is an issue with the gem calling the rake task?

**Comment by dickeyxxx** [comment]
it's an issue with the rake task calling the toolbelt

**Comment by marcamillion** [comment]
Ok Thanks.
