### ISSUE TITLE
Error "couldn't find HOME environment -- expanding `~'"

### ISSUE THREAD

**Issue by lukehorvat** [heroku/toolbelt#133]
Running the `heroku` command produces this error:
 
```
couldn't find HOME environment -- expanding `~'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/lib/heroku/helpers.rb:13:in `home'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/lib/heroku/helpers.rb:13:in `home_directory'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/lib/heroku/updater.rb:14:in `updating_lock_path'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/lib/heroku/updater.rb:187:in `warn_if_updating'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/lib/heroku/cli.rb:21:in `start'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/bin/heroku:24:in `<main>'
couldn't find HOME environment -- expanding `~'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/lib/heroku/helpers.rb:13:in `home'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/lib/heroku/helpers.rb:13:in `home_directory'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/lib/heroku/plugin.rb:41:in `directory'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/lib/heroku/plugin.rb:45:in `list'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/lib/heroku/helpers.rb:429:in `format_error'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/lib/heroku/helpers.rb:454:in `styled_error'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/lib/heroku/cli.rb:39:in `rescue in start'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/lib/heroku/cli.rb:19:in `start'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/bin/heroku:24:in `<main>'
couldn't find HOME environment -- expanding `~'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/lib/heroku/helpers.rb:13:in `home'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/lib/heroku/helpers.rb:13:in `home_directory'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/lib/heroku/updater.rb:14:in `updating_lock_path'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/lib/heroku/updater.rb:187:in `warn_if_updating'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/lib/heroku/cli.rb:21:in `start'
/usr/local/Cellar/heroku-toolbelt/3.41.5/libexec/bin/heroku:24:in `<main>'
```

I am using rbenv. The local Ruby version in this directory is 1.9.2. If I change the version to 1.9.3 it works successfully. Is this a bug or does toolbelt no longer work with < 1.9.3?

**Comment by dickeyxxx** [comment]
1.9.3+ only

**Comment by dickeyxxx** [comment]
if you use the OS X package instead of homebrew it will use 1.9.3 and you can keep 1.9.2 in your path
