### ISSUE TITLE
Heroku pg:ps `require': cannot load such file -- net/ssh/gateway (LoadError)

### ISSUE THREAD

**Issue by starrychloe** [heroku/toolbelt#169]
```
C:\Users\Chloe\workspace\bestsales>heroku version
heroku/toolbelt/3.42.45 (i386-mingw32) ruby/1.9.3
heroku-cli/5.2.34-65b16c9 (windows-386) go1.6.2
=== Installed Plugins
heroku-pg-transfer


C:\Users\Chloe\workspace\bestsales>heroku pg:ps
C:/Program Files (x86)/Heroku/ruby-1.9.2/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot
load such file -- net/ssh/gateway (LoadError)
        from C:/Program Files (x86)/Heroku/ruby-1.9.2/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Users/Chloe/.heroku/client/lib/heroku/helpers/heroku_postgresql.rb:54:in `maybe_tunnel'
        from C:/Users/Chloe/.heroku/client/lib/heroku/command/pg.rb:780:in `exec_sql'
        from C:/Users/Chloe/.heroku/client/lib/heroku/command/pg.rb:752:in `version'
        from C:/Users/Chloe/.heroku/client/lib/heroku/command/pg.rb:759:in `nine_two?'
        from C:/Users/Chloe/.heroku/client/lib/heroku/command/pg.rb:763:in `pid_column'
        from C:/Users/Chloe/.heroku/client/lib/heroku/command/pg.rb:290:in `ps'
        from C:/Users/Chloe/.heroku/client/lib/heroku/command.rb:212:in `run'
        from C:/Users/Chloe/.heroku/client/lib/heroku/cli.rb:33:in `start'
        from C:/Program Files (x86)/Heroku/bin/heroku:32:in `<main>'
```

**Comment by ransombriggs** [comment]
@starrychloe Could you please re-install the CLI from https://toolbelt.heroku.com/ ?  The CLI code itself is up to date, but we do not attempt to update the ruby interpreter and since you first installed the CLI, it has bumped from `ruby-1.9.2` to `ruby-2.1.7`.

**Comment by starrychloe** [comment]
OK.

```
C:\Users\Chloe\workspace\bestsales>heroku version
heroku/toolbelt/3.43.9 (i386-mingw32) ruby/2.1.7
heroku-cli/5.2.34-65b16c9 (windows-386) go1.6.2
=== Installed Plugins
heroku-pg-transfer


C:\Users\Chloe\workspace\bestsales>heroku pg:ps
DL is deprecated, please use Fiddle
 !    The local psql command could not be located
 !    For help installing psql, see https://devcenter.heroku.com/articles/heroku-postgresql#local-setup
```

I only have `psql` installed under Cygwin.

```
Chloe@xps ~/workspace/bestsales
$ heroku pg:ps
DL is deprecated, please use Fiddle
  pid  | state  | source |   running_for    | waiting |                   query
-------+--------+--------+------------------+---------+--------------------------------------------
 24494 | active |        | -00:00:00.001122 | f       | SELECT * FROM "keyword" WHERE "keyword"=$1
(1 row)
```

**Comment by ransombriggs** [comment]
@starrychloe it appears to be working now, is it alright if I close?
