### ISSUE TITLE
Heroku Toolbelt issue with Gemfile specifying ruby version.

### ISSUE THREAD

**Issue by Nerian** [heroku/toolbelt#63]
Hi,

I ran into some issues while using `heroku run` with in a project with a Gemfile that specifies a ruby version ( `ruby '2.0.0'`)

I created a repo with the minimal things to reproduce the issue:

https://github.com/Nerian/heroku_ticket_94846

**Comment by okoriko** [comment]
```
/Users/eurico/.rbenv/versions/2.1.5/gemsets/catch/gems/bundler-1.7.6/lib/bundler/definition.rb:380:in `validate_ruby!': Your Ruby version is 1.9.3, but your Gemfile specified 2.1.5 (Bundler::RubyVersionMismatch)
	from /Users/eurico/.rbenv/versions/2.1.5/gemsets/catch/gems/bundler-1.7.6/lib/bundler.rb:117:in `setup'
	from /Users/eurico/.rbenv/versions/2.1.5/gemsets/catch/gems/bundler-1.7.6/lib/bundler/setup.rb:17:in `<top (required)>'
	from /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
```

**Comment by okoriko** [comment]
that's what i got

**Comment by Nerian** [comment]
@dickeyxxx 

What I did was change the ruby version Heroku toolbelt uses by modifying the first line of the heroku script.

```
➜  Nerian  which heroku
/usr/bin/heroku
➜  Nerian  cat /usr/bin/heroku
#!/Users/Nerian/.rvm/rubies/default/bin/ruby
...
```
